{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7f18b4ff-fcf1-4385-b625-545bc537d502",
   "metadata": {},
   "outputs": [],
   "source": [
    "from xgboost import XGBClassifier\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, roc_auc_score, f1_score\n",
    "from sklearn.naive_bayes import GaussianNB, BernoulliNB\n",
    "from sklearn.neighbors import NearestCentroid\n",
    "from sklearn.discriminant_analysis import LinearDiscriminantAnalysis\n",
    "from lightgbm import LGBMClassifier\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
    "from sklearn.feature_selection import RFE\n",
    "from xgboost import XGBClassifier\n",
    "from sklearn.linear_model import (\n",
    "    LogisticRegression,\n",
    "    SGDClassifier,\n",
    "    Perceptron,\n",
    "    RidgeClassifier,\n",
    "    RidgeClassifierCV\n",
    ")\n",
    "from lazypredict.Supervised import LazyClassifier\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "# Define models and hyperparameter grids\n",
    "models = {\n",
    "    'LogisticRegression': LogisticRegression(),\n",
    "    'RandomForestClassifier': RandomForestClassifier(\n",
    "        random_state=42\n",
    "    ),\n",
    "    'GradientBoosting': GradientBoostingClassifier(\n",
    "        random_state=42\n",
    "    ),\n",
    "    'XGBoostClassifier': XGBClassifier(\n",
    "        objective='binary:logistic',\n",
    "        eval_metric='logloss',\n",
    "        random_state=42\n",
    "    ),\n",
    "    'LGBMClassifier': LGBMClassifier(\n",
    "        random_state=42,\n",
    "        verbose=-1\n",
    "    ),\n",
    "    'SGDClassifier': SGDClassifier(\n",
    "        random_state=42\n",
    "    ),\n",
    "    'BernoulliNB': BernoulliNB(),\n",
    "    'GaussianNB': GaussianNB(),\n",
    "    'NearestCentroid': NearestCentroid(),\n",
    "    'Perceptron': Perceptron(\n",
    "        random_state=42\n",
    "    ),\n",
    "    'LinearDiscriminantAnalysis': LinearDiscriminantAnalysis(),\n",
    "    'RidgeClassifier': RidgeClassifier(),\n",
    "    'RidgeClassifierCV': RidgeClassifierCV()\n",
    "}\n",
    "\n",
    "model_grids = {\n",
    "\n",
    "    'LogisticRegression': {},\n",
    "\n",
    "    'RandomForestClassifier': {\n",
    "        'n_estimators': [100, 200, 300],\n",
    "        'max_depth': [1, 5]\n",
    "    },\n",
    "\n",
    "    'GradientBoosting': {\n",
    "        'n_estimators': [100, 200, 300, 400, 500],\n",
    "        'learning_rate': [0.01, 0.05, 0.1, 0.2],\n",
    "        'max_depth': [3, 4, 5, 6, 7, 8]\n",
    "    },\n",
    "\n",
    "    'XGBoostClassifier': {\n",
    "        'n_estimators': [100, 200, 300],\n",
    "        'max_depth': [2, 3, 4, 5],\n",
    "        'learning_rate': [0.01, 0.05, 0.1],\n",
    "        'subsample': [0.8, 0.9],\n",
    "        'colsample_bytree': [0.8, 0.9]\n",
    "    },\n",
    "\n",
    "    'LGBMClassifier': {\n",
    "        'n_estimators': [100, 200, 300],\n",
    "        'learning_rate': [0.01, 0.05, 0.1],\n",
    "        'max_depth': [3, 5, 7]\n",
    "    },\n",
    "\n",
    "    'SGDClassifier': {\n",
    "        'loss': ['log_loss', 'hinge'],\n",
    "        'alpha': [0.0001, 0.001, 0.01]\n",
    "    },\n",
    "\n",
    "    'BernoulliNB': {\n",
    "        'alpha': [0.1, 0.5, 1.0]\n",
    "    },\n",
    "\n",
    "    'GaussianNB': {},\n",
    "\n",
    "    'NearestCentroid': {},\n",
    "\n",
    "    'Perceptron': {\n",
    "        'penalty': [None, 'l2'],\n",
    "        'alpha': [0.0001, 0.001]\n",
    "    },\n",
    "\n",
    "    'LinearDiscriminantAnalysis': {},\n",
    "\n",
    "    'RidgeClassifier': {\n",
    "        'alpha': [0.1, 1.0, 10.0]\n",
    "    },\n",
    "\n",
    "    'RidgeClassifierCV': {}\n",
    "}\n",
    "\n",
    "data_path = '../../data/processed/ACME-HappinessSurvey2020.csv' \n",
    "data = pd.read_csv(data_path)\n",
    "X = data.drop('Y', axis=1)\n",
    "y = data['Y']\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "# Use XGBoost for RFE to stay consistent\n",
    "xgb_model = XGBClassifier(objective='binary:logistic',\n",
    "        random_state=42)\n",
    "\n",
    "xgb_model.fit(X_train, y_train)\n",
    "\n",
    "# RFE\n",
    "rfe_selector = RFE(estimator=xgb_model, n_features_to_select=3)\n",
    "rfe_selector.fit(X_train, y_train)\n",
    "rfe_selected_features = X.columns[rfe_selector.support_]\n",
    "rfe_ignored_features = X.columns[~rfe_selector.support_]\n",
    "\n",
    "print(\"✅ Top 3 Selected Features by RFE:\")\n",
    "for feature in rfe_selected_features:\n",
    "    print(f\" - {feature}\")\n",
    "\n",
    "print(\"\\n❌ Features Ignored by RFE:\")\n",
    "for feature in rfe_ignored_features:\n",
    "    print(f\" - {feature}\")\n",
    "\n",
    "# Store for config\n",
    "selected_features_dict = {\n",
    "    'rfe': list(rfe_selected_features)\n",
    "}\n",
    "\n",
    "# Filter datasets to use only selected features for experimentation\n",
    "X_train = X[rfe_selected_features]\n",
    "X_test = X[rfe_selected_features]\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X_train, y, test_size=0.2, random_state=42, stratify= y)\n",
    "scaler = StandardScaler()\n",
    "\n",
    "#Fit the scaler on train feature set\n",
    "X_train = scaler.fit_transform(X_train)\n",
    "\n",
    "\n",
    "X_test = scaler.transform(X_test)\n",
    "\n",
    "clf = LazyClassifier(verbose=1,ignore_warnings=True, custom_metric=None, random_state = 42)\n",
    "models,predictions = clf.fit(X_train, X_test, y_train, y_test)\n",
    "\n",
    "models\n",
    "\n",
    "import mlflow\n",
    "\n",
    "mlflow_tracking_uri = 'http://localhost:5555'  \n",
    "if mlflow_tracking_uri:\n",
    "    mlflow.set_tracking_uri(mlflow_tracking_uri)\n",
    "    mlflow.set_experiment(\"Customer_Happiness\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
